# Generated by Django 6.0.8 on 2026-09-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='du')),
                ('end_date', models.DateField(verbose_name='au')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='motif')),
            ],
            options={
                'verbose_name': 'fermeture',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True, verbose_name='jour')),
                ('is_closed', models.BooleanField(default=False, verbose_name='fermé')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='ouverture')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='fermeture')),
            ],
            options={
                'verbose_name': "horaire d'ouverture",
                'verbose_name_plural': "horaires d'ouverture",
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='référence')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='début')),
                ('end_at', models.DateTimeField(db_index=True, verbose_name='fin prévue')),
                ('status', models.CharField(choices=[('pending', 'À confirmer'), ('confirmed', 'Confirmé'), ('received', 'Véhicule reçu'), ('in_progress', 'En cours'), ('quality_check', 'Contrôle final'), ('done', 'Terminé'), ('delivered', 'Livré'), ('cancelled', 'Annulé'), ('refused', 'Refusé'), ('no_show', 'Absent'), ('rescheduled', 'Reporté')], db_index=True, default='pending', max_length=20, verbose_name='statut')),
                ('price_estimate', models.PositiveIntegerField(blank=True, null=True, verbose_name='prix estimé (FCFA)')),
                ('customer_notes', models.TextField(blank=True, verbose_name='instructions du client')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='catalog.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'rendez-vous',
                'verbose_name_plural': 'rendez-vous',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='appointments.appointment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historique de statut',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
