# Generated by Django 6.0.8 on 2026-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'À confirmer'), ('confirmed', 'Confirmé'), ('received', 'Véhicule reçu'), ('in_progress', 'En cours'), ('quality_check', 'Contrôle final'), ('done', 'Terminé'), ('delivered', 'Restitué'), ('cancelled', 'Annulé'), ('refused', 'Refusé'), ('no_show', 'Absent'), ('rescheduled', 'Reporté')], db_index=True, default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
