# Generated by Django 6.0.8 on 2026-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'séquence',
            },
        ),
    ]
