# Generated by Django 6.0.8 on 2026-10-02 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60, verbose_name='action')),
                ('object_type', models.CharField(max_length=60, verbose_name="type d'objet")),
                ('object_id', models.CharField(max_length=40, verbose_name='identifiant')),
                ('object_repr', models.CharField(max_length=200, verbose_name='objet')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
