# Generated by Django 6.0.8 on 2026-10-02 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_restitue_label'),
        ('customers', '0002_contactrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='numéro')),
                ('issued_at', models.DateTimeField(verbose_name='émise le')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='remise (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='mentions')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='annulée le')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name="motif d'annulation")),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'facture',
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='désignation')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantité')),
                ('unit_price', models.PositiveIntegerField(verbose_name='prix unitaire (FCFA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'ligne de facture',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='montant (FCFA)')),
                ('method', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('card', 'Carte bancaire'), ('cash', 'Espèces'), ('transfer', 'Virement')], max_length=15, verbose_name='moyen de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='référence de transaction')),
                ('received_at', models.DateTimeField(db_index=True, verbose_name='reçu le')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='remboursé le')),
                ('refund_reason', models.CharField(blank=True, max_length=200, verbose_name='motif du remboursement')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paiement',
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('cancelled_at__isnull', True)), fields=('appointment',), name='one_active_invoice_per_appointment'),
        ),
    ]
