# Generated by Django 6.0.8 on 2026-10-02 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_restitue_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('inspection', 'Inspection à la réception'), ('before', 'Avant'), ('after', 'Après')], max_length=12, verbose_name='type')),
                ('image', models.ImageField(upload_to='appointments/%Y/%m/', verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='appointments.appointment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "photo d'intervention",
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
                ('title', models.CharField(max_length=150, verbose_name='étape')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='validée le')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='appointments.appointment')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'étape de traitement',
                'ordering': ['appointment', 'order'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'order'), name='unique_step_order')],
            },
        ),
    ]
