# Generated by Django 6.0.8 on 2026-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('detailing', 'Detailing'), ('cleaning', 'Nettoyage'), ('polishing', 'Polissage'), ('protection', 'Protection'), ('preparation', 'Préparation')], max_length=20, verbose_name='catégorie')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='résumé')),
                ('description', models.TextField(blank=True, verbose_name='description détaillée')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Prix fixe'), ('from', 'À partir de'), ('quote', 'Sur devis')], default='from', max_length=10, verbose_name='tarification')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='prix (FCFA)')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='durée planifiée (min)')),
                ('duration_label', models.CharField(blank=True, max_length=40, verbose_name='durée affichée')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='image')),
                ('benefits', models.JSONField(blank=True, default=list, verbose_name='bénéfices')),
                ('process_steps', models.JSONField(blank=True, default=list, verbose_name='protocole')),
                ('is_active', models.BooleanField(default=True, verbose_name='réservable')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'prestation',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
