# Generated by Django 6.0.8 on 2026-09-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('full_name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('job_title', models.CharField(max_length=100, verbose_name='fonction')),
                ('specialty', models.CharField(blank=True, max_length=150, verbose_name='spécialité')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('busy', 'Occupé'), ('break', 'En pause'), ('absent', 'Absent')], default='available', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "membre de l'équipe",
                'verbose_name_plural': 'équipe',
                'ordering': ['full_name'],
            },
        ),
    ]
