# Generated by Django 6.0.8 on 2026-10-02 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('value', models.CharField(max_length=30, verbose_name='valeur')),
                ('label', models.CharField(max_length=120, verbose_name='libellé')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié (chiffre vérifié)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'chiffre clé',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('author', models.CharField(max_length=120, verbose_name='auteur')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='fonction / précision')),
                ('vehicle_label', models.CharField(blank=True, max_length=150, verbose_name='véhicule')),
                ('quote', models.TextField(verbose_name='avis')),
                ('consent_obtained', models.BooleanField(default=False, verbose_name='accord écrit du client pour publication')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'avis client',
                'verbose_name_plural': 'avis clients',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('vehicle_label', models.CharField(max_length=150, verbose_name='véhicule')),
                ('category', models.CharField(choices=[('detailing', 'Detailing'), ('cleaning', 'Nettoyage'), ('polishing', 'Polissage'), ('protection', 'Protection'), ('preparation', 'Préparation')], max_length=20, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('services_performed', models.CharField(blank=True, max_length=300, verbose_name='prestations réalisées')),
                ('duration_label', models.CharField(blank=True, max_length=50, verbose_name='durée')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='réalisé le')),
                ('before_image', models.ImageField(upload_to='gallery/%Y/', verbose_name='photo avant')),
                ('after_image', models.ImageField(upload_to='gallery/%Y/', verbose_name='photo après')),
                ('is_published', models.BooleanField(default=False, verbose_name='publié')),
                ('featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réalisation',
                'ordering': ['-featured', 'sort_order', '-completed_on', '-id'],
            },
        ),
    ]
