# Generated by Django 6.0.8 on 2026-09-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('brand', models.CharField(max_length=60, verbose_name='marque')),
                ('model', models.CharField(max_length=80, verbose_name='modèle')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='année')),
                ('registration', models.CharField(max_length=20, verbose_name='immatriculation')),
                ('color', models.CharField(blank=True, max_length=60, verbose_name='couleur')),
                ('fuel', models.CharField(blank=True, choices=[('diesel', 'Diesel'), ('petrol', 'Essence'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], max_length=10, verbose_name='motorisation')),
                ('photo_url', models.URLField(blank=True, verbose_name='photo')),
                ('notes', models.TextField(blank=True, verbose_name='notes atelier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer')),
            ],
            options={
                'verbose_name': 'véhicule',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'registration'), name='unique_registration_per_customer')],
            },
        ),
    ]
