# Generated by Django 6.0.8 on 2026-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, upload_to='vehicles/%Y/%m/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='image externe'),
        ),
    ]
