# Generated by Django 6.0.8 on 2026-09-30 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('full_name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone / WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('segment', models.CharField(choices=[('new', 'Nouveau'), ('active', 'Actif'), ('vip', 'VIP')], default='new', max_length=10)),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'client',
                'ordering': ['-created_at'],
            },
        ),
    ]
