# Generated by Django 6.0.8 on 2026-09-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('full_name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('message', models.TextField(verbose_name='message')),
                ('handled', models.BooleanField(default=False, verbose_name='traité')),
            ],
            options={
                'verbose_name': 'demande de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
